namespace BackendTZ.DTOs.Responses;

/// <summary>
/// Base class for all report/analytics related responses.
/// </summary>
public abstract record ReportResponse;

/// <summary>
/// Represents revenue generated by a single room over a reporting period.
/// </summary>
/// <param name="RoomId">The ID of the room.</param>
/// <param name="RoomName">The name of the room.</param>
/// <param name="TotalRevenue">The total revenue generated, in UAH.</param>
/// <param name="BookingsCount">The number of bookings in the period.</param>
public record RoomRevenueResponse(
    Guid RoomId,
    string RoomName,
    decimal TotalRevenue,
    int BookingsCount
) : ReportResponse;

/// <summary>
/// Represents the occupancy rate of a room over a reporting period.
/// </summary>
/// <param name="RoomId">The ID of the room.</param>
/// <param name="RoomName">The name of the room.</param>
/// <param name="BookedHours">The total number of hours booked.</param>
/// <param name="AvailableHours">The total number of hours theoretically available in the period.</param>
/// <param name="OccupancyRate">The occupancy rate, from 0.0 to 1.0.</param>
public record RoomOccupancyResponse(
    Guid RoomId,
    string RoomName,
    decimal BookedHours,
    decimal AvailableHours,
    double OccupancyRate
) : ReportResponse;

/// <summary>
/// Represents the popularity of an additional service over a reporting period.
/// </summary>
/// <param name="ServiceId">The ID of the service.</param>
/// <param name="ServiceName">The name of the service.</param>
/// <param name="TimesBooked">The number of bookings that included this service.</param>
/// <param name="TotalRevenue">The total revenue generated by this service, in UAH.</param>
public record ServicePopularityResponse(
    Guid ServiceId,
    string ServiceName,
    int TimesBooked,
    decimal TotalRevenue
) : ReportResponse;

/// <summary>
/// Represents the average booking value ("середній чек") over a reporting period.
/// </summary>
/// <param name="AverageCost">The average total cost per booking, in UAH.</param>
/// <param name="BookingsCount">The number of bookings used to calculate the average.</param>
public record AverageBookingValueResponse(
    decimal AverageCost,
    int BookingsCount
) : ReportResponse;