using BackendTZ.Entities;

namespace BackendTZ.DTOs.Responses;

/// <summary>
/// Base class for all report related responses.
/// </summary>
public abstract record ReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo
);

/// <summary>
/// Granularity used to bucket a report's data over time.
/// </summary>
public enum ReportGroupBy
{
    /// <summary>
    /// Aggregate all data into a single bucket for the entire reporting period.
    /// </summary>
    Day,

    /// <summary>
    /// Aggregate data into daily buckets for the reporting period.
    /// </summary>
    Week,

    /// <summary>
    /// Aggregate data into weekly buckets for the reporting period.
    /// </summary>
    Month
}


/// <summary>
/// Revenue aggregated for a single time bucket (e.g. one day, one week).
/// </summary>
/// <param name="Period">Label identifying the bucket (e.g. "2024-09-01", "2024-W35").</param>
/// <param name="Revenue">Total revenue generated within this bucket.</param>
/// <param name="BookingsCount">Number of bookings that contributed to this bucket.</param>
public record RevenueByPeriodResponse(
    string Period,
    decimal Revenue,
    int BookingsCount
);

/// <summary>
/// Revenue aggregated for a single room.
/// </summary>
/// <param name="RoomId">The ID of the room.</param>
/// <param name="RoomName">The name of the room, captured as of the report run.</param>
/// <param name="Revenue">Total revenue generated by this room.</param>
/// <param name="IsActive">Whether the room is still active (false if since deactivated/deleted).</param>
public record RevenueByRoomResponse(
    Guid RoomId,
    string RoomName,
    decimal Revenue,
    bool IsActive
);

/// <summary>
/// Represents the revenue report for a given period.
/// </summary>
/// <param name="DateFrom">Start of the reporting period (inclusive).</param>
/// <param name="DateTo">End of the reporting period (inclusive).</param>
/// <param name="TotalRevenue">Total revenue across the whole period (sum of total_cost).</param>
/// <param name="BaseRentalRevenue">Portion of revenue coming from base room rental (sum of base_cost, net of time adjustment).</param>
/// <param name="ServicesRevenue">Portion of revenue coming from additional services (sum of services_cost).</param>
/// <param name="Breakdown">Revenue broken down by time bucket.</param>
/// <param name="ByRoom">Revenue broken down by room.</param>
public record RevenueReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    decimal TotalRevenue,
    decimal BaseRentalRevenue,
    decimal ServicesRevenue,
    List<RevenueByPeriodResponse> Breakdown,
    List<RevenueByRoomResponse> ByRoom
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// Utilization metrics for a single room over the reporting period.
/// </summary>
/// <param name="RoomId">The ID of the room.</param>
/// <param name="RoomName">The name of the room.</param>
/// <param name="AvailableHours">Total hours the room was available for booking (excludes periods where is_available was false, if tracked historically).</param>
/// <param name="BookedHours">Total hours the room was actually booked.</param>
/// <param name="UtilizationPercent">Booked hours as a percentage of available hours.</param>
/// <param name="IsActive">Whether the room is still active.</param>
public record RoomUtilizationResponse(
    Guid RoomId,
    string RoomName,
    decimal AvailableHours,
    decimal BookedHours,
    decimal UtilizationPercent,
    bool IsActive
);

/// <summary>
/// Represents the room utilization report for a given period.
/// </summary>
/// <param name="DateFrom">Start of the reporting period (inclusive).</param>
/// <param name="DateTo">End of the reporting period (inclusive).</param>
/// <param name="Rooms">Utilization metrics per room.</param>
public record RoomUtilizationReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    List<RoomUtilizationResponse> Rooms
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// A room's ranking by number of bookings.
/// </summary>
public record RoomByBookingsCountResponse(
    Guid RoomId,
    string RoomName,
    int BookingsCount
);

/// <summary>
/// A room's ranking by revenue generated.
/// </summary>
public record RoomByRevenueResponse(
    Guid RoomId,
    string RoomName,
    decimal Revenue
);

/// <summary>
/// Represents the popular rooms report for a given period.
/// </summary>
public record PopularRoomsReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    List<RoomByBookingsCountResponse> ByBookingsCount,
    List<RoomByRevenueResponse> ByRevenue
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// Usage and revenue metrics for a single additional service.
/// </summary>
/// <param name="ServiceId">The ID of the service.</param>
/// <param name="ServiceName">The name of the service.</param>
/// <param name="TimesOrdered">Number of bookings that included this service.</param>
/// <param name="TotalRevenue">Total revenue generated by this service, computed from booking_services.price_at_booking (not the current live price).</param>
/// <param name="IsActive">Whether the service is still active/offered.</param>
public record ServiceUsageResponse(
    Guid ServiceId,
    string ServiceName,
    int TimesOrdered,
    decimal TotalRevenue,
    bool IsActive
);

/// <summary>
/// Represents the popular services report for a given period.
/// </summary>
public record PopularServicesReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    List<ServiceUsageResponse> Services
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// Represents aggregate booking statistics for a given period.
/// </summary>
/// <param name="DateFrom">Start of the reporting period (inclusive).</param>
/// <param name="DateTo">End of the reporting period (inclusive).</param>
/// <param name="TotalBookings">Total number of bookings created within the period.</param>
/// <param name="CancelledBookings">Number of bookings with status = Cancelled.</param>
/// <param name="CancellationRatePercent">Cancelled bookings as a percentage of total bookings.</param>
/// <param name="AverageDurationHours">Average booking duration, derived from end_time - start_time.</param>
/// <param name="AverageCheckAmount">Average total_cost per booking.</param>
public record BookingStatisticsResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    int TotalBookings,
    int CancelledBookings,
    decimal CancellationRatePercent,
    decimal AverageDurationHours,
    decimal AverageCheckAmount
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// Identifies one of the pricing periods used when calculating booking cost.
/// </summary>
public enum PricingPeriodType
{
    /// <summary>
    /// Bookings that start in the morning period (e.g. 6am-12pm).
    /// </summary>
    Morning,

    /// <summary>
    /// Bookings that start in the standard period (e.g. 12pm-6pm).
    /// </summary>
    Standard,

    /// <summary>
    /// Bookings that start in the peak period (e.g. 6pm-12am).
    /// </summary>
    Peak,

    /// <summary>
    /// Bookings that start in the evening period (e.g. 12am-6am).
    /// </summary>
    Evening
}

/// <summary>
/// Bookings and revenue attributed to a single pricing period.
/// </summary>
public record PricingPeriodBreakdownResponse(
    PricingPeriodType PeriodType,
    int BookingsCount,
    decimal Revenue
);

/// <summary>
/// Represents the pricing period breakdown report for a given period.
/// </summary>
public record PricingPeriodReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    List<PricingPeriodBreakdownResponse> Periods
) : ReportResponse(DateFrom, DateTo);

/// <summary>
/// A single client's ranking by spend within the reporting period.
/// </summary>
/// <param name="ClientId">The ID of the user (users.id).</param>
/// <param name="ClientName">The name of the user.</param>
/// <param name="ClientEmail">The email of the user, useful for follow-up/marketing.</param>
/// <param name="TotalSpent">Total amount spent (sum of total_cost across their bookings).</param>
/// <param name="BookingsCount">Total number of bookings made by this client.</param>
public record ClientSpendingResponse(
    Guid ClientId,
    string ClientName,
    string ClientEmail,
    decimal TotalSpent,
    int BookingsCount
);

/// <summary>
/// Represents the top clients report for a given period.
/// </summary>
public record TopClientsReportResponse(
    DateOnly DateFrom,
    DateOnly DateTo,
    List<ClientSpendingResponse> Clients
) : ReportResponse(DateFrom, DateTo);